eels:
  evm-bin: ethereum-spec-evm-resolver
  x-dist: auto
geth:
  evm-bin: evm
  x-dist: auto
evmone:
  evm-bin: evmone-t8n
  x-dist: auto
besu:
  evm-bin: evmtool
  x-dist: 0
ethjs:
  evm-bin: ethereumjs-t8ntool.sh
  x-dist: auto