name: Build and Package Fixtures
inputs:
  name:
    description: 'Name of the fixture package'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install yq
      shell: bash
      run: |
        pip install yq
    - name: Extract fixture properties
      id: properties
      shell: bash
      run: |
        yq -r --arg feature "${{ inputs.name }}" '.[$feature] | to_entries | map("\(.key)=\(.value)")[]' ./.github/configs/feature.yaml >> "$GITHUB_OUTPUT"
    - uses: ./.github/actions/build-evm-base
      id: evm-builder
      with:
        type: ${{ steps.properties.outputs.evm-type }}
    - name: Run fixtures fill
      shell: bash
      run: |
        pip install --upgrade pip
        python -m venv env
        source env/bin/activate
        pip install -e .
        solc-select use  ${{ steps.properties.outputs.solc }} --always-install
        fill -n ${{ steps.evm-builder.outputs.x-dist }} --evm-bin=${{ steps.evm-builder.outputs.evm-bin }} ${{ steps.properties.outputs.fill-params }} --output=fixtures_${{ inputs.name }}.tar.gz --build-name ${{ inputs.name }}
    - uses: actions/upload-artifact@v4
      with:
        name: fixtures_${{ inputs.name }}
        path: fixtures_${{ inputs.name }}.tar.gz