"""
EOF v1 validation code
"""

import pytest
from ethereum_test_tools import EOFTestFiller
from ethereum_test_tools.eof.v1 import Container, EOFException

@pytest.mark.parametrize(
    "eof_code,expected_hex_bytecode,exception",
    [
        pytest.param(
            Container(
                name="EOF1V00001",
                raw_bytes=bytes(
                     [
                        0xef,
                        0x00,
                        0x01,
                        0x01,
                        0x00,
                        0x04,
                        0x02,
                        0x00,
                        0x01,
                        0x00,
                        0x03,
                        0x04,
                        0x00,
                        0x00,
                        0x00,
                        0x00,
                        0x80,
                        0x00,
                        0x00,
                        0xe0,
                        0xff,
                        0xfd,

                     ]),
            ),
            "0xef000101000402000100030400000000800000e0fffd",
            None,
            id="backwards_rjump_0",
        ),
        pytest.param(
            Container(
                name="EOF1V00002",
                raw_bytes=bytes(
                     [
                        0xef,
                        0x00,
                        0x01,
                        0x01,
                        0x00,
                        0x04,
                        0x02,
                        0x00,
                        0x01,
                        0x00,
                        0x05,
                        0x04,
                        0x00,
                        0x00,
                        0x00,
                        0x00,
                        0x80,
                        0x00,
                        0x01,
                        0x5f,
                        0x50,
                        0xe0,
                        0xff,
                        0xfb,

                     ]),
            ),
            "0xef0001010004020001000504000000008000015f50e0fffb",
            None,
            id="backwards_rjump_1",
        ),
        pytest.param(
            Container(
                name="EOF1V00003",
                raw_bytes=bytes(
                     [
                        0xef,
                        0x00,
                        0x01,
                        0x01,
                        0x00,
                        0x04,
                        0x02,
                        0x00,
                        0x01,
                        0x00,
                        0x0d,
                        0x04,
                        0x00,
                        0x00,
                        0x00,
                        0x00,
                        0x80,
                        0x00,
                        0x01,
                        0x5f,
                        0x50,
                        0x60,
                        0x01,
                        0xe1,
                        0x00,
                        0x03,
                        0xe0,
                        0xff,
                        0xf8,
                        0xe0,
                        0xff,
                        0xf5,

                     ]),
            ),
            "0xef0001010004020001000d04000000008000015f506001e10003e0fff8e0fff5",
            None,
            id="backwards_rjump_2",
        ),
        pytest.param(
            Container(
                name="EOF1V00004",
                raw_bytes=bytes(
                     [
                        0xef,
                        0x00,
                        0x01,
                        0x01,
                        0x00,
                        0x04,
                        0x02,
                        0x00,
                        0x01,
                        0x00,
                        0x0e,
                        0x04,
                        0x00,
                        0x00,
                        0x00,
                        0x00,
                        0x80,
                        0x00,
                        0x01,
                        0x5f,
                        0x50,
                        0x60,
                        0x01,
                        0xe1,
                        0x00,
                        0x03,
                        0xe0,
                        0xff,
                        0xf8,
                        0x5f,
                        0xe0,
                        0xff,
                        0xf4,

                     ]),
            ),
            "0xef0001010004020001000e04000000008000015f506001e10003e0fff85fe0fff4",
            EOFException.INVALID_STACK_HEIGHT,
            id="backwards_rjump_3",
        ),
        pytest.param(
            Container(
                name="EOF1V00005",
                raw_bytes=bytes(
                     [
                        0xef,
                        0x00,
                        0x01,
                        0x01,
                        0x00,
                        0x04,
                        0x02,
                        0x00,
                        0x01,
                        0x00,
                        0x04,
                        0x04,
                        0x00,
                        0x00,
                        0x00,
                        0x00,
                        0x80,
                        0x00,
                        0x01,
                        0x5f,
                        0xe0,
                        0xff,
                        0xfc,

                     ]),
            ),
            "0xef0001010004020001000404000000008000015fe0fffc",
            EOFException.INVALID_STACK_HEIGHT,
            id="backwards_rjump_4",
        ),
        pytest.param(
            Container(
                name="EOF1V00006",
                raw_bytes=bytes(
                     [
                        0xef,
                        0x00,
                        0x01,
                        0x01,
                        0x00,
                        0x04,
                        0x02,
                        0x00,
                        0x01,
                        0x00,
                        0x05,
                        0x04,
                        0x00,
                        0x00,
                        0x00,
                        0x00,
                        0x80,
                        0x00,
                        0x01,
                        0x5f,
                        0x50,
                        0xe0,
                        0xff,
                        0xfc,

                     ]),
            ),
            "0xef0001010004020001000504000000008000015f50e0fffc",
            EOFException.INVALID_STACK_HEIGHT,
            id="backwards_rjump_5",
        ),
        
    ]
)

def test_example_valid_invalid(
    eof_test: EOFTestFiller,
    eof_code: Container,
    expected_hex_bytecode: str,
    exception: EOFException | None,
):
    """
    Verify eof container construction and exception
    """
    if expected_hex_bytecode[0:2] == "0x":
        expected_hex_bytecode = expected_hex_bytecode[2:]
    assert bytes(eof_code) == bytes.fromhex(expected_hex_bytecode)

    eof_test(
        data=eof_code,
        expect_exception=exception,
    )
