name: 'Build evmone EVM'
description: 'Builds the evmone EVM binary'
inputs:
  repo:
    description: 'Source repository to use to build the EVM binary'
    required: true
    default: 'ethereum/evmone'
  ref:
    description: 'Reference to branch, commit, or tag to use to build the EVM binary'
    required: true
    default: 'master'
  targets:
    description: 'Which targets to build from evmone repo'
    required: false
    default: 'all'
runs:
  using: "composite"
  steps:
    - name: Checkout evmone
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}
        path: evmone
        submodules: true
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
    - name: "Install GMP"
      shell: bash
      run: sudo apt-get -q update && sudo apt-get -qy install libgmp-dev
    - name: Build evmone binary
      shell: bash
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        cd $GITHUB_WORKSPACE/evmone
        cmake -S . -B build -DEVMONE_TESTING=ON -DEVMONE_PRECOMPILES_SILKPRE=1
        cmake --build build --parallel --target ${{ inputs.targets }}
        echo $GITHUB_WORKSPACE/evmone/build/bin/ >> $GITHUB_PATH
