name: 'Setup UV'
description: 'Sets up uv with a fixed version'
runs:
  using: 'composite'
  steps:
    - name: Install UV
      shell: bash
      run: |
        UV_VERSION="0.5.20"
        echo "Installing UV version $UV_VERSION..."
        curl -LsSf https://astral.sh/uv/${UV_VERSION}/install.sh | sh
