"""
EOF V1 Constants used throughout all tests
"""
EOF_FORK_NAME = "Prague"

MAX_CODE_SECTIONS = 1024

MAX_RETURN_STACK_HEIGHT = 1024

MAX_OPERAND_STACK_HEIGHT = 1023

MAX_CODE_INPUTS = 127

MAX_CODE_OUTPUTS = 127

MAX_RJUMPV_COUNT = 0xFF

MAX_BYTECODE_SIZE = 24576

MAX_INITCODE_SIZE = MAX_BYTECODE_SIZE * 2
