""""
EOF v1 validation code - Exported from evmone unit tests
"""

import pytest
from ethereum_test_tools import EOFTestFiller, EOFException
from ethereum_test_tools.eof.v1 import Container, Section

REFERENCE_SPEC_GIT_PATH = "EIPS/eip-3540.md"
REFERENCE_SPEC_VERSION = "12ca2f0bd2f7380100e154aaaa0995c46cbb2710"

@pytest.mark.parametrize(
    "eof_code,expected_hex_bytecode,exception",
    [
        pytest.param(
              Container(
                  name="EOFV1_0001",
                  raw_bytes=(
                      [
                          0xef,
                          0x00,
                          0x01,
                          0x05,
                          0x00,
                          0x01,
                          0x00,
                          0xfe,
                      ]),
              ),
              "ef000105000100fe",
              EOFException.MISSING_TYPE_HEADER,
              id="eof1_unknown_section_0"
        ),
        pytest.param(
              Container(
                  name="EOFV1_0002",
                  raw_bytes=(
                      [
                          0xef,
                          0x00,
                          0x01,
                          0xff,
                          0x00,
                          0x01,
                          0x00,
                          0xfe,
                      ]),
              ),
              "ef0001ff000100fe",
              EOFException.MISSING_TYPE_HEADER,
              id="eof1_unknown_section_1"
        ),
        pytest.param(
              Container(
                  name="EOFV1_0003",
                  raw_bytes=(
                      [
                          0xef,
                          0x00,
                          0x01,
                          0x01,
                          0x00,
                          0x04,
                          0x02,
                          0x00,
                          0x01,
                          0x00,
                          0x01,
                          0x05,
                          0x00,
                          0x01,
                          0x00,
                          0x00,
                          0x80,
                          0x00,
                          0x00,
                          0xfe,
                          0x00,
                      ]),
              ),
              "ef000101000402000100010500010000800000fe00",
              EOFException.MISSING_DATA_SECTION,
              id="eof1_unknown_section_2"
        ),
        pytest.param(
              Container(
                  name="EOFV1_0004",
                  raw_bytes=(
                      [
                          0xef,
                          0x00,
                          0x01,
                          0x01,
                          0x00,
                          0x04,
                          0x02,
                          0x00,
                          0x01,
                          0x00,
                          0x01,
                          0xff,
                          0x00,
                          0x01,
                          0x00,
                          0x00,
                          0x80,
                          0x00,
                          0x00,
                          0xfe,
                          0x00,
                      ]),
              ),
              "ef00010100040200010001ff00010000800000fe00",
              EOFException.MISSING_DATA_SECTION,
              id="eof1_unknown_section_3"
        ),
        pytest.param(
              Container(
                  name="EOFV1_0005",
                  raw_bytes=(
                      [
                          0xef,
                          0x00,
                          0x01,
                          0x01,
                          0x00,
                          0x04,
                          0x02,
                          0x00,
                          0x01,
                          0x00,
                          0x01,
                          0x04,
                          0x00,
                          0x01,
                          0x05,
                          0x00,
                          0x01,
                          0x00,
                          0x00,
                          0x80,
                          0x00,
                          0x00,
                          0xfe,
                          0xaa,
                          0x00,
                      ]),
              ),
              "ef000101000402000100010400010500010000800000feaa00",
              EOFException.MISSING_TERMINATOR,
              id="eof1_unknown_section_4"
        ),
        pytest.param(
              Container(
                  name="EOFV1_0006",
                  raw_bytes=(
                      [
                          0xef,
                          0x00,
                          0x01,
                          0x01,
                          0x00,
                          0x04,
                          0x02,
                          0x00,
                          0x01,
                          0x00,
                          0x01,
                          0x04,
                          0x00,
                          0x01,
                          0xff,
                          0x00,
                          0x01,
                          0x00,
                          0x00,
                          0x80,
                          0x00,
                          0x00,
                          0xfe,
                          0xaa,
                          0x00,
                      ]),
              ),
              "ef00010100040200010001040001ff00010000800000feaa00",
              EOFException.MISSING_TERMINATOR,
              id="eof1_unknown_section_5"
        ),
        
    ]
)

def test_example_valid_invalid(
    eof_test: EOFTestFiller,
    eof_code: Container,
    expected_hex_bytecode: str,
    exception: EOFException | None,
):
    """
    Verify eof container construction and exception
    """
    assert bytes(eof_code) == bytes.fromhex(expected_hex_bytecode)

    eof_test(
        data=eof_code,
        expect_exception=exception,
    )
