name: Deploy Docs

permissions:
  pages: write # Required for deploying to GitHub Pages with `secrets.GITHUB_TOKEN`

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # Push events to matching v*, i.e. v1.0, v20.15.10, v0.1.1a1
    branches:
      - main

jobs:
  deploy:
    if: github.repository_owner == 'ethereum' # don't run on forks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          ssh-key: ${{secrets.GH_ACTIONS_DEPLOY_KEY}}
      - name: Build transition tool
        uses: ./.github/actions/build-evm-base
        with:
          id: evm-builder
          type: stable
      - name: Set up uv
        uses: ./.github/actions/setup-uv
      - name: Set up Python
        run: uv python install 3.11
      - name: Install EEST and dependencies
        run: uv sync --extra=docs --no-progress
      - name: Setup doc deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email github-actions[bot]@users.noreply.github.com
      - name: Build and deploy docs to gh-pages
        if: ${{ github.ref_type == 'branch' }}
        run: |
            uv run mike deploy --update-aliases --push --remote origin main development
      - name: Build and deploy docs to gh-pages
        if: ${{ github.ref_type == 'tag' }}
        run: |
          uv run mike deploy --push --remote origin ${{ github.ref_name }}
